void:
	echo "Indicar número da tarefa (e.g.: make 1)"

1:
	gcc -o tarefa1 tarefa1.cpp -lGL -lGLU -lglut
	rm -f *.o
	
2:
	gcc -o tarefa2 tarefa2.cpp -lGL -lGLU -lglut
	rm -f *.o
	
3:
	gcc -o tarefa3 tarefa3.cpp -lGL -lGLU -lglut
	rm -f *.o
	
limpar:
	rm -f tarefa1 tarefa2 tarefa3
